service: workshop-${self:custom.name}

custom:
  name: Greg
  email: greg.campion@paessler.com

provider:
  name: aws
  runtime: nodejs12.x
  profile: playground

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
