version: 2.1
orbs:
  node: circleci/node@1.1

jobs:
  integration-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run test # run our integration tests

  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run set-credentials
            - run: npm run sls -- deploy -s e2e-test-<< pipeline.git.branch >>

  acceptance-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run acceptance

  test-env-teardown:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run set-credentials
            - run: npm run sls -- remove -s e2e-test-<< pipeline.git.branch >>

workflows:
  version: 3
  dev:
    jobs:
      - integration-test
      - deploy:
          requires:
            - integration-test
      - acceptance-test:
          requires:
            - deploy
      - test-env-teardown:
          requires:
            - acceptance-test
